replicaCount: 3

image:
  repository: "444062204470.dkr.ecr.eu-west-1.amazonaws.com/order-service"
  tag: "1.0.0"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
